### ISSUE TITLE
Пожалуйста обновите версию до 1.10+

### ISSUE THREAD

**Issue by King0fHell** [genisyspromcpe/LiteCore#8]
### Описание
Пожалуйста обновите до 1.10+
### Причины
1. Все постепенно переходят на новые версии, и 1.1 уже многим надоел
2. Многие пользователи iOS не могут играть на серверах с версией 1.1 т.к. практический все обновляются до самого нового релиза, и откат у них уже не возможен(конечно же если есть JailBreak, то можно все))
3. У меня на телефоне версия 1.12, а на ПК 1.1, только для того что бы было удобнее работать с сервером, а хочется играть на новой версии и с ПК(

**Comment by genisyspromcpe** [comment]
> ### Описание
> Пожалуйста обновите до 1.10+
> 
> ### Причины
> 1. Все постепенно переходят на новые версии, и 1.1 уже многим надоел
> 2. Многие пользователи iOS не могут играть на серверах с версией 1.1 т.к. практический все обновляются до самого нового релиза, и откат у них уже не возможен(конечно же если есть JailBreak, то можно все))
> 3. У меня на телефоне версия 1.12, а на ПК 1.1, только для того что бы было удобнее работать с сервером, а хочется играть на новой версии и с ПК(

легко сказать

**Comment by yoraze** [comment]
> > ### Описание
> > Пожалуйста обновите до 1.10+
> > ### Причины
> > 
> > 1. Все постепенно переходят на новые версии, и 1.1 уже многим надоел
> > 2. Многие пользователи iOS не могут играть на серверах с версией 1.1 т.к. практический все обновляются до самого нового релиза, и откат у них уже не возможен(конечно же если есть JailBreak, то можно все))
> > 3. У меня на телефоне версия 1.12, а на ПК 1.1, только для того что бы было удобнее работать с сервером, а хочется играть на новой версии и с ПК(
> 
> легко сказать

сделать впринципе тоже изи, если знаешь, как делать.

**Comment by genisyspromcpe** [comment]
> > > ### Описание
> > > Пожалуйста обновите до 1.10+
> > > ### Причины
> > > 
> > > 1. Все постепенно переходят на новые версии, и 1.1 уже многим надоел
> > > 2. Многие пользователи iOS не могут играть на серверах с версией 1.1 т.к. практический все обновляются до самого нового релиза, и откат у них уже не возможен(конечно же если есть JailBreak, то можно все))
> > > 3. У меня на телефоне версия 1.12, а на ПК 1.1, только для того что бы было удобнее работать с сервером, а хочется играть на новой версии и с ПК(
> > 
> > 
> > легко сказать
> 
> сделать впринципе тоже изи, если знаешь, как делать.

сначала, хотелось бы пофиксить чанки.

**Comment by BeyCoder** [comment]
Лучше мультиверсию сделать

**Comment by marker98** [comment]
> Лучше мультиверсию сделать

Если тебе лучше, то сам и делай. Ядро отлично справляется с возложенными на него задачами. Улучшать может и стоит, но кардинально менять его сруктуру и принципы, чтобы сделать тебе мультиверсию - глупо и очень опрометчиво. Причем мультиверсия уже реализована в другом ядре и если тебе так нужно, можешь воспользоваться им.

**Comment by yoraze** [comment]
> > Лучше мультиверсию сделать
> 
> Если тебе лучше, то сам и делай. Ядро отлично справляется с возложенными на него задачами. Улучшать может и стоит, но кардинально менять его сруктуру и принципы, чтобы сделать тебе мультиверсию - глупо и очень опрометчиво. Причем мультиверсия уже реализована в другом ядре и если тебе так нужно, можешь воспользоваться им.

НОРМАЛЬНЫХ ядер с мультиверсией ещё не существует В ОТКРЫТОМ ДОСТУПЕ. Пользоваться SteadFast2 как по моему - слишком глупо, у них мультиверсия как и само ядро полное говнище.

Какие-либо фиксы не помогут, там надо всё ядро выбросить в помойку и написать заново.
