### ISSUE TITLE
Добавьте unregister В SimpleCommandMap

### ISSUE THREAD

**Issue by rusinc** [genisyspromcpe/LiteCore#9]
### Описание
Очень не хватает возможности удалять ванильные команды методом "из коробки", как это реализовано в других ядрах (например, Steadfast или pocketmine).
Пример реализации можно посмотреть [здесь (steadfast)](https://github.com/Hydreon/Steadfast2/blob/8eed3dd97371eab4b3d7a62b5bd66dae7859ffc4/src/pocketmine/command/SimpleCommandMap.php#L265) или [здесь (pocketmine)](https://github.com/pmmp/PocketMine-MP/blob/a19143cae76ad55f1bdc2f39ad007b1fc170980b/src/pocketmine/command/SimpleCommandMap.php#L185) (но в pocketmine, кажется, это выглядит более корректно)

### Причины
Ванильные команды не всегда нужны (например, если хочется собственную реализацию банов или телепортаций), но с помощью плагинов удалить их из списка команд сейчас невозможно (только если редактировать ядро).

**Comment by genisyspromcpe** [comment]
Будет добавлено в течении месяца, ожидайте.

**Comment by marker98** [comment]
Плюсую. Очень не хватает. Так же было бы круто, если бы интелект мобов и воды можно было отключать конфигом или в плагине.
